Repository assimbly/runtime, pull requests merged in 2023-06, with the labels that each got.

#130 Added new release workflow & deleted old publish action
  .github/workflows/new-release.yml
  .github/workflows/release-publish.yml
Labels: skip-release, workflows

#131 Release 4.0.1
  .github/workflows/manual-update-version.yml
  .github/workflows/new-release.yml
  .github/workflows/release-publish.yml
  broker/pom.xml
  brokerRest/pom.xml
  dil/pom.xml
  dil/src/main/java/org/assimbly/dil/blocks/beans/AggregateStrategy.java
  dil/src/main/java/org/assimbly/dil/blocks/beans/enrich/EnrichStrategy.java
  dil/src/main/java/org/assimbly/dil/blocks/beans/enrich/attachment/AttachmentEnrichStrategy.java
  dil/src/main/java/org/assimbly/dil/blocks/beans/enrich/json/JsonEnrichStrategy.java
  dil/src/main/java/org/assimbly/dil/blocks/beans/enrich/override/OverrideEnrichStrategy.java
  dil/src/main/java/org/assimbly/dil/blocks/beans/json/JsonAggregateStrategy.java
  dil/src/main/java/org/assimbly/dil/blocks/connections/Connection.java
  dil/src/main/java/org/assimbly/dil/blocks/connections/broker/AMQPConnection.java
  dil/src/main/java/org/assimbly/dil/blocks/processors/FailureProcessor.java
  dil/src/main/java/org/assimbly/dil/blocks/processors/SetHeadersProcessor.java
  dil/src/main/java/org/assimbly/dil/event/EventConfigurer.java
  dil/src/main/java/org/assimbly/dil/event/collect/MessageCollector.java
  dil/src/main/java/org/assimbly/dil/event/domain/MessageEvent.java
  dil/src/main/java/org/assimbly/dil/event/store/impl/FileStore.java
  dil/src/main/java/org/assimbly/dil/loader/FlowLoader.java
  dil/src/main/java/org/assimbly/dil/transpiler/XMLFileConfiguration.java
  dil/src/main/java/org/assimbly/dil/transpiler/marshalling/Marshall.java
  dil/src/main/java/org/assimbly/dil/transpiler/marshalling/Unmarshall.java
  dil/src/main/java/org/assimbly/dil/transpiler/marshalling/core/Route.java
  dil/src/main/java/org/assimbly/dil/transpiler/marshalling/core/RouteConfiguration.java
  dil/src/main/java/org/assimbly/dil/transpiler/marshalling/core/RouteTemplate.java
  dil/src/main/java/org/assimbly/dil/transpiler/ssl/SSLConfiguration.java
  dil/src/main/java/org/assimbly/dil/transpiler/transform/Transform.java
  dil/src/main/java/org/assimbly/dil/validation/FtpValidator.java
  dil/src/main/java/org/assimbly/dil/validation/HttpsCertificateValidator.java
  dil/src/main/java/org/assimbly/dil/validation/XsltValidator.java
  dil/src/main/java/org/assimbly/dil/validation/expressions/JsonPathValidator.java
  dil/src/main/java/org/assimbly/dil/validation/https/CompositeTrustManager.java
  dil/src/main/java/org/assimbly/dil/validation/https/FileBasedTrustStore.java
  dil/src/main/resources/transform-to-dil.xsl
  integration/pom.xml
  integration/src/main/java/org/assimbly/integration/impl/BaseIntegration.java
  integration/src/main/java/org/assimbly/integration/impl/CamelIntegration.java
  integrationRest/pom.xml
  integrationRest/src/main/java/org/assimbly/integrationrest/CertificateManagerRuntime.java
  integrationRest/src/main/java/org/assimbly/integrationrest/IntegrationRuntime.java
  integrationRest/src/main/java/org/assimbly/integrationrest/ValidationRuntime.java
  integrationRest/src/main/java/org/assimbly/integrationrest/event/FailureCollector.java
  integrationRest/src/test/java/org/assimbly/integrationrest/utils/CamelContextUtil.java
  integrationRest/src/test/java/org/assimbly/integrationrest/utils/MavenUtil.java
  pom.xml
Labels: patch

#132 Updated new release workflow
  .github/workflows/new-release.yml
Labels: feature

#133 Updated workflows
  .github/workflows/maven-publish.yml
  .github/workflows/new-release.yml
Labels: feature

#134 Added delete-packages workflow
  .github/workflows/delete-packages.yml
Labels: feature

#135 Updated delete-packages workflow
  .github/workflows/delete-packages.yml
Labels: bug, feature

#136 health check endpoint - jvm stats
  dil/src/main/java/org/assimbly/dil/validation/stats/BackendResponse.java
  integration/src/main/java/org/assimbly/integration/Integration.java
  integration/src/main/java/org/assimbly/integration/impl/CamelIntegration.java
  integrationRest/src/main/java/org/assimbly/integrationrest/StatisticsRuntime.java
Labels: feature
